version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    environment:
      - REDIS_HOST=redis
    ports:
      - 8081:8081
    depends_on:
      - redis
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - 8080:8080
    extra_hosts:
      - "scalway: 51.15.227.152"
  redis:
    image: redis
