version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    environment:
      - REDIS_HOST=redis
    ports:
      - 8081:8081
    depends_on:
      - redis
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
      networks:
      app_net:
        ipv4_address: 51.15.227.152
        ipv6_address: 2001:bc8:624:1300::1
    ports:
      - 8080:8080
  redis:
    image: redis

  networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "51.15.227.152"
        - subnet: "2001:bc8:624:1300::1"
